"""add chat_messages table

Revision ID: 027a54473dd3
Revises: 4258932762e7
Create Date: 2026-09-18 15:25:18.893846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027a54473dd3'
down_revision: Union[str, Sequence[str], None] = '4258932762e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('selected_element_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('proposed_diff', sa.JSON(), nullable=True),
    sa.Column('needs_confirmation', sa.Boolean(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('declined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_process_id'), 'chat_messages', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_process_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
