"""add registry entries table

Revision ID: 18432a86c163
Revises: fa06e1dfafd5
Create Date: 2026-09-20 23:35:45.921977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18432a86c163'
down_revision: Union[str, Sequence[str], None] = 'fa06e1dfafd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('registry_name', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('source_process_id', sa.String(), nullable=True),
    sa.Column('source_node_ids', sa.JSON(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pushed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pushed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_process_id'], ['processes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_entries_registry_name'), 'registry_entries', ['registry_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_entries_registry_name'), table_name='registry_entries')
    op.drop_table('registry_entries')
    # ### end Alembic commands ###
