"""add blueprint overlays table

Revision ID: 229b93e87377
Revises: 304f26b53f34
Create Date: 2026-09-19 01:54:23.801258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229b93e87377'
down_revision: Union[str, Sequence[str], None] = '304f26b53f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprint_overlays',
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('baseline_version_id', sa.String(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blueprint_overlays')
    # ### end Alembic commands ###
