"""initial schema

Revision ID: 2a0c8924e27b
Revises: 
Create Date: 2026-09-18 07:01:53.523613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a0c8924e27b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector doesn't auto-add this -- required before any table can use
    # the VECTOR column type (see local-stack-bootstrap skill).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actors_process_id'), 'actors', ['process_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_process_id'), 'documents', ['process_id'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.create_index('ix_document_embeddings_embedding_cosine', 'document_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('process_elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('inputs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('outputs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('systems_touched', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_elements_process_id'), 'process_elements', ['process_id'], unique=False)
    op.create_table('process_schema_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_schema_changes_process_id'), 'process_schema_changes', ['process_id'], unique=False)
    op.create_table('process_flows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('from_element_id', sa.String(), nullable=False),
    sa.Column('to_element_id', sa.String(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_element_id'], ['process_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_element_id'], ['process_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_flows_process_id'), 'process_flows', ['process_id'], unique=False)
    op.create_table('source_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['element_id'], ['process_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_refs_element_id'), 'source_refs', ['element_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_refs_element_id'), table_name='source_refs')
    op.drop_table('source_refs')
    op.drop_index(op.f('ix_process_flows_process_id'), table_name='process_flows')
    op.drop_table('process_flows')
    op.drop_index(op.f('ix_process_schema_changes_process_id'), table_name='process_schema_changes')
    op.drop_table('process_schema_changes')
    op.drop_index(op.f('ix_process_elements_process_id'), table_name='process_elements')
    op.drop_table('process_elements')
    op.drop_index('ix_document_embeddings_embedding_cosine', table_name='document_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_documents_process_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_actors_process_id'), table_name='actors')
    op.drop_table('actors')
    op.drop_table('processes')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
