"""add bpmn_drafts table

Revision ID: 4258932762e7
Revises: 2a0c8924e27b
Create Date: 2026-09-18 08:18:55.050146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4258932762e7'
down_revision: Union[str, Sequence[str], None] = '2a0c8924e27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bpmn_drafts',
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('low_confidence_element_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bpmn_drafts')
    # ### end Alembic commands ###
