"""add digital twin tables

Revision ID: 83365370d5d2
Revises: 18432a86c163
Create Date: 2026-09-21 13:44:07.928092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83365370d5d2'
down_revision: Union[str, Sequence[str], None] = '18432a86c163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twin_scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_artifact_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('system_stubs', sa.JSON(), nullable=False),
    sa.Column('human_checkpoint_config', sa.JSON(), nullable=False),
    sa.Column('expected_steps', sa.JSON(), nullable=False),
    sa.Column('expected_outputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_artifact_id'], ['agent_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twin_scenarios_agent_artifact_id'), 'twin_scenarios', ['agent_artifact_id'], unique=False)
    op.create_table('twin_tool_schemas',
    sa.Column('agent_artifact_id', sa.String(), nullable=False),
    sa.Column('schemas', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_artifact_id'], ['agent_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_artifact_id')
    )
    op.create_table('twin_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('agent_artifact_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('final_output', sa.JSON(), nullable=True),
    sa.Column('deviations', sa.JSON(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('turns_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_artifact_id'], ['agent_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['twin_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twin_runs_agent_artifact_id'), 'twin_runs', ['agent_artifact_id'], unique=False)
    op.create_index(op.f('ix_twin_runs_scenario_id'), 'twin_runs', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twin_runs_scenario_id'), table_name='twin_runs')
    op.drop_index(op.f('ix_twin_runs_agent_artifact_id'), table_name='twin_runs')
    op.drop_table('twin_runs')
    op.drop_table('twin_tool_schemas')
    op.drop_index(op.f('ix_twin_scenarios_agent_artifact_id'), table_name='twin_scenarios')
    op.drop_table('twin_scenarios')
    # ### end Alembic commands ###
