"""add agent publications table

Revision ID: 9b055947e7f9
Revises: 9c0e2068ec0f
Create Date: 2026-09-21 16:49:02.004741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b055947e7f9'
down_revision: Union[str, Sequence[str], None] = '9c0e2068ec0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_publications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_artifact_id', sa.String(), nullable=False),
    sa.Column('registry_name', sa.String(), nullable=False),
    sa.Column('registry_entry_id', sa.String(), nullable=False),
    sa.Column('source_artifact_generated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_by', sa.String(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_artifact_id'], ['agent_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_publications_agent_artifact_id'), 'agent_publications', ['agent_artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_publications_agent_artifact_id'), table_name='agent_publications')
    op.drop_table('agent_publications')
    # ### end Alembic commands ###
