"""add twin baseline table

Revision ID: 9c0e2068ec0f
Revises: 83365370d5d2
Create Date: 2026-09-21 14:14:28.490296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0e2068ec0f'
down_revision: Union[str, Sequence[str], None] = '83365370d5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twin_baselines',
    sa.Column('agent_artifact_id', sa.String(), nullable=False),
    sa.Column('typical_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_artifact_id'], ['agent_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('agent_artifact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twin_baselines')
    # ### end Alembic commands ###
