"""add users, sessions, and attribution columns

Revision ID: 9ff873b841f5
Revises: a4ed9c0f258a
Create Date: 2026-09-19 16:12:41.096360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff873b841f5'
down_revision: Union[str, Sequence[str], None] = 'a4ed9c0f258a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.add_column('gap_findings', sa.Column('decided_by', sa.String(), nullable=True))
    # Named explicitly (autogenerate left these unnamed, which downgrade()
    # can't reference) -- this project has no naming convention configured
    # on Base.metadata, and every FK added before this migration was on
    # CREATE TABLE, never ALTER TABLE ADD COLUMN, so this is the first
    # migration to hit it.
    op.create_foreign_key(
        'fk_gap_findings_decided_by_users', 'gap_findings', 'users', ['decided_by'], ['id'], ondelete='SET NULL'
    )
    op.add_column('versions', sa.Column('created_by', sa.String(), nullable=True))
    op.create_foreign_key(
        'fk_versions_created_by_users', 'versions', 'users', ['created_by'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_versions_created_by_users', 'versions', type_='foreignkey')
    op.drop_column('versions', 'created_by')
    op.drop_constraint('fk_gap_findings_decided_by_users', 'gap_findings', type_='foreignkey')
    op.drop_column('gap_findings', 'decided_by')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
