"""add gap findings table

Revision ID: a4ed9c0f258a
Revises: 229b93e87377
Create Date: 2026-09-19 07:50:02.003669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ed9c0f258a'
down_revision: Union[str, Sequence[str], None] = '229b93e87377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('target_element_ids', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('chosen_option_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_findings_process_id'), 'gap_findings', ['process_id'], unique=False)
    op.add_column('processes', sa.Column('gap_analysis_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'gap_analysis_completed_at')
    op.drop_index(op.f('ix_gap_findings_process_id'), table_name='gap_findings')
    op.drop_table('gap_findings')
    # ### end Alembic commands ###
