"""add agent artifacts table

Revision ID: fa06e1dfafd5
Revises: 9ff873b841f5
Create Date: 2026-09-20 16:17:02.644177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa06e1dfafd5'
down_revision: Union[str, Sequence[str], None] = '9ff873b841f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=False),
    sa.Column('node_ids', sa.JSON(), nullable=False),
    sa.Column('primary_node_id', sa.String(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('source_baseline_version_id', sa.String(), nullable=False),
    sa.Column('source_node_snapshot', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'group_key', name='uq_agent_artifacts_process_group')
    )
    op.create_index(op.f('ix_agent_artifacts_process_id'), 'agent_artifacts', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_artifacts_process_id'), table_name='agent_artifacts')
    op.drop_table('agent_artifacts')
    # ### end Alembic commands ###
